# LLM
LLAMAPARSE_API_KEY=<LLAMAPARSE_API_KEY>
GEMINI_API_KEY=<GEMINI_API_KEY>

# POSTGRES
POSTGRES_USERNAME=<POSTGRES_USERNAME>
POSTGRES_PASSWORD=<POSTGRES_PASSWORD>
POSTGRES_DATABASE_NAME=<POSTGRES_DATABASE_NAME>
POSTGRES_HOST=database
POSTGRES_PORT=5432
POSTGRES_AUTO_MIGRATE=True

# ENVIRONMENT (DEV/PROD)
ENV=DEV

# LANGFUSE
LANGFUSE_SECRET_KEY=<LANGFUSE_SECRET_KEY>
LANGFUSE_PUBLIC_KEY=<LANGFUSE_PUBLIC_KEY>
LANGFUSE_BASE_URL=https://cloud.langfuse.com